project:
    type: website
    output-dir: docs
    preview:
        browser: true
    # resources:
    #     - CV_canatara.pdf
    render:
        - "*.qmd"
        - "!blog"

website:
    title: "Abdulkadir Canatar"
    description: "Personal Webpage"
    site-url: https://canatara.github.io/
    repo-url: https://github.com/canatara/canatara.github.io
    search: false
    google-analytics: G-59DYNC14NL
    page-navigation: false
    back-to-top-navigation: true
    bread-crumbs: false
    page-footer:
        center: "Â© 2025 Abdulkadir Canatar. All rights reserved."
    navbar:
        title: "Abdulkadir Canatar"
        left:
            - text: Home
              href: index.qmd
            - text: CV
              href: cv.qmd
            - text: Publications
              href: publications.qmd
        right:
            - text: "{{< ai google-scholar-square >}}"
              href: https://scholar.google.com/citations?user=_F4TER8AAAAJ
              target: _blank
            - icon: github
              href: https://github.com/canatara
              target: _blank
            - icon: linkedin
              href: https://www.linkedin.com/in/canatara/
              target: _blank
            - icon: twitter-x
              href: https://x.com/canatar_a
              target: _blank
            - text: "{{< ai orcid >}}"
              href: https://orcid.org/0000-0002-0140-5718
              target: _blank

format:
    html:
        theme: cosmo
        fontsize: 1.1em
        linestretch: 1.5
        toc: false
        code-copy: true
        smooth-scroll: true
        link-external-newwindow: true
execute:
    freeze: auto
